version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet publish -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts\Koans
test_script:
- dotnet test -c %CONFIGURATION%
cache:
- '%USERPROFILE%\.nuget\packages'
#on_finish:
#- dotnet artifacts\Koans\DotNetCoreKoans.dll